spring:
  datasource:
    url: jdbc:h2:mem:catalogdb
    driver-class-name: org.h2.Driver
  jpa:
    hibernate:
      ddl-auto: create-drop
    database-platform: org.hibernate.dialect.H2Dialect
    show-sql: true

logging:
  level:
    com.soulf.catalog: DEBUG
    org.springframework.web: DEBUG

